
outputFolder : "Results"
dataFolder : "../NPP_data"
allGenesFile : "NPP_all_genes.csv"
nppFilePrefix : "Homo_sapiens_NPP"
ROCFolder : "../Test1_ROC_multiple_methods"
# ES_results_title : "Enrichment Scores for NPP before/after filtering"
# results_file_prefix : "ES_filtered"
ES_results_title : "ES Z-scores for NPP with different correlations"
results_file_prefix : "ES_zscores_correlations_newpalette"

NPPs : ["UniProt_062018"]
CORRELATIONs : ["pearson", "spearman", "kendall"]

npp_colors:
  UniProt_062018__pearson : "royalblue3"
  UniProt_062018__spearman : "#c77cff"
  UniProt_062018__kendall : "#661174"

npp_nice_names:
  UniProt_062018__pearson : "pearson"
  UniProt_062018__spearman : "spearman"
  UniProt_062018__kendall : "kendall"

# NPPs : ["UniProt_sqrt", "UniProt_062018", "UniProt_1_divide_x", "UniProt_1_divide_sqrt", "UniProt_1_divide_x^2", "UniProt_1_divide_x^3"]
# CORRELATIONs : ["pearson"]
#
# npp_colors:
#   UniProt_sqrt : "#7FC97F" # (light green)
#   UniProt_062018 : "#F0027F" # (pink)
#   UniProt_1_divide_x : "#BEAED4" # (lilach)
#   UniProt_1_divide_sqrt : "#FDC086" # (gentle orange)
#   'UniProt_1_divide_x^2' : "#FFFF99" # (light yellow)
#   'UniProt_1_divide_x^3' : "#386CB0" # (silent blue)
#
# npp_nice_names:
#   UniProt_sqrt : "sqrt(x)"
#   UniProt_062018 : "log2(x)"
#   UniProt_1_divide_x : "1/x"
#   UniProt_1_divide_sqrt : "1/sqrt(x)"
#   'UniProt_1_divide_x^2' : "1/(x^2)"
#   'UniProt_1_divide_x^3' : "1/(x^3)"

# NPPs_from_file : TRUE
# combinations_list_file : "combinations_list.csv"
# combinations_details_file : "combinations_details.csv"

# NPPs_from_file : FALSE
# NPPs : ["UniProt_062018"]
# CORRELATIONs : ["pearson"]

# NPPs : ["UniProt_062018", "UniProt_112018_FILT"]
# CORRELATIONs : ["pearson"]
#
# npp_colors:
#   UniProt_112018_FILT: "#7FC97F" # (light green)
#   UniProt_062018 : "#F0027F" # (pink)
#
# npp_nice_names:
#   UniProt_112018_FILT: "AFTER filtering"
#   UniProt_062018 : "BEFORE filtering"

# NPP : "UniProt_062018"
#

# NPPs : ["UniProt_062018", "UniProt_no_divide_by_query"]
# CORRELATIONs : ["pearson"]
#
# npp_colors:
#   UniProt_no_divide_by_query : "#7FC97F" # (light green)
#   UniProt_062018 : "#F0027F" # (pink)
#
# npp_nice_names:
#   UniProt_no_divide_by_query : "no dividing"
#   UniProt_062018 : "divide by query"

# NPPs : ["UniProt_062018", "UniProt_no_col_zscore"]
# CORRELATIONs : ["pearson"]


# NPPs : ["UniProt_062018", "UniProt_log2_before_divide"]
# CORRELATIONs : ["pearson"]
#
# npp_colors:
#   UniProt_log2_before_divide : "#7FC97F" # (light green)
#   UniProt_062018 : "#F0027F" # (pink)
#
# npp_nice_names:
#   UniProt_log2_before_divide : "log2 BEFORE divide"
#   UniProt_062018 : "log2 AFTER divide"


# NPPs : ["UniProt_062018", "UniProt_no_threshold", "UniProt_threshold_40", "UniProt_threshold_20.4_after_zscore", "UniProt_floored_0.01", "UniProt_floored_0.05"]
# CORRELATIONs : ["pearson"] # ["pearson", "spearman", "kendall"]
#
# npp_colors:
#   UniProt_062018 : "#7FC97F" # (light green)
#   UniProt_no_threshold : "#F0027F" # (pink)
#   UniProt_threshold_40 : "#BEAED4" # (lilach)
#   'UniProt_threshold_20.4_after_zscore' : "#FDC086" # (gentle orange)
#   'UniProt_floored_0.01' : "#FFFF99" # (light yellow)
#   'UniProt_floored_0.05' : "#386CB0" # (silent blue)
#
# npp_nice_names:
#   UniProt_062018 : "threshold 20.4"
#   UniProt_no_threshold : "no threshold"
#   UniProt_threshold_40 : "threshold 40"
#   'UniProt_threshold_20.4_after_zscore' : "threshold 20.4 after zscore"
#   'UniProt_floored_0.01' : "late flooring 0.01"
#   'UniProt_floored_0.05' : "late flooring 0.05"

# npp_colors: - from "I want hue" - not distinctive enough
#   UniProt_062018 : "#5e9600" # (light green)
#   UniProt_no_threshold : "#7b3588" # (violet)
#   UniProt_threshold_40 : "#ff90ba" # (light pink)
#   'UniProt_threshold_20.4_after_zscore' : "#d33914" # (orange)
#   'UniProt_floored_0.01' : "#0096c9" # (light blue)
#   'UniProt_floored_0.05' : "#864450" # (obergin)


  # UniProt_062018 : "red"
  # UniProt_no_threshold : "blue"
  # UniProt_threshold_40 : "green"
  # UniProt_threshold_60 : "purple"
  # 'UniProt_floored_0.01' : "brown"
  # 'UniProt_floored_0.05' : "pink"

# > brewer.pal(6,  "Accent")
# [1] "#7FC97F" (light green) "#BEAED4" (lilach) "#FDC086" (gentle orange)
# "#FFFF99" (light yellow)  "#386CB0" (silent blue) "#F0027F" (pink)
 # "#DD6F8B" "#DAC183" "#9EE36F" "#9CDCCE" "#B0A8D3" "#BA60DF"

# geneCollectionResource : "MSigDB"
# geneGroupsRootFolder : "../Gene_sets"
# collectionsFile : "gmt_files.csv"
# collectionID : 5
# collectionName : "c2.cp.kegg.v6.0.symbols"

# geneCollectionResource : "Random" # "KeggFromAPI"
# geneGroupsRootFolder : "../Gene_sets"
# collectionsFile : "random_files.csv" # "kegg_files.csv"
# collectionID : 2
# collectionName : "random_100_groups_size_90_seed123" # "random_kegg_sizes_genes" # "kegg_pathway_genes" #
# collectionNiceName : "RANDOM 100 groups seed 123"

geneCollectionResource : "KeggFromAPI"
geneGroupsRootFolder : "../Gene_sets"
collectionsFile : "kegg_files.csv"
collectionID : 1 # 2
collectionName : "kegg_pathway_genes" # "random_kegg_sizes_genes" #
collectionNiceName : "KEGG pathways" # "RANDOM pathways with KEGG sizes"

# collectionSizes : [ 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
#                   31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
#                   47, 48, 49, 50, 51, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 65,
#                   66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 82, 83,
#                   84, 85, 86, 88, 89, 90, 91, 92, 93, 95, 96, 97, 99, 100, 101,
#                   102, 103, 104, 106, 107, 108, 112, 113, 114, 116, 118, 119, 120,
#                   121, 123, 124, 127, 128, 130, 131, 133, 134, 136, 137, 138, 139,
#                   142, 143, 144, 145, 146, 147, 148, 149, 150, 152, 153, 154, 160,
#                   162, 163, 164, 165, 168, 170, 171, 173, 175, 179, 180, 182, 185,
#                   186, 193, 198, 199, 200, 201, 206, 208, 229, 232, 244, 255, 270,
#                   277, 295, 299, 319, 352 ]
collectionSizes : [ 15, 30, 50, 100, 350]
smoothRandom : TRUE

randomTimes : 1000
randomBinSize : 100

suffix : "_offset_add1" # "_zeroed"
randomFolderSuffix : "_random"
write_RES_to_file : FALSE

numOfGenes : 20192 # 19232
